### ISSUE TITLE
Word selection by API selections have has so far been bad and often even had special characters in it

### ISSUE THREAD

**Issue by Sephem** [mithom/streamlabs_chatbot_hangman#1]
hi the hangman API keep selecting really obscure and sometimes non English words.  Can we not try and specify something in the API that selects easier and more common words The selections I have has so far have all been bad and often even had special characters in it

**Comment by mithom** [comment]
dear stephen, In the latest version, the words have already improved. For this i incorporated a MinCorpusCount of 200. I've been thinking to raise it even more, but it looked already decent without special characters to me. If you already are on latest version, Please let me know and I'll increase the 200. Selecting types of words won't work sadly enough because they have to many categories and their api design only allows in/exclusion of 1 category. So that would narrow it down too much

**Comment by mithom** [comment]
after checking what words are in the 200-500 and 500-1000 range, i decided to raise the minCorpusCount to 500. Please let know if this has solved your problem

**Comment by mithom** [comment]
d40d6779b753f54c7bdc463c96400642470f4b3e solves this issue
